FROM node:14

WORKDIR /workspace

RUN npm install -g @angular/cli
COPY package*.json ./
RUN npm install
COPY . ./
RUN chmod -Rv 777 src/*

EXPOSE 4200

CMD [ "ng", "serve", "--host", "0.0.0.0", "--disable-host-check" ]


#### Considering that we are in the current directory

### Build image
## docker build -t dev.todo.api -f Dockerfile.dev .
# -t: the target is the name of the image,
# we will refere it when run it the container

### Run container 
## docker run -p 80:4200 --name dev.todo.api dev.todo.api
# -d: detachable mode
# -p: port mapping
# -v: volume mapping
# --name: the name of the container
# at last i specified the image name to run the container