FROM nginx:1.19.10-alpine

RUN apk add --update npm

WORKDIR /app

COPY package*.json ./
RUN npm install
RUN npm install -g @angular/cli
COPY . ./
RUN ng build

COPY ./nginx.conf  /etc/nginx/conf.d/default.conf
COPY ./dist/app  /usr/share/nginx/html

EXPOSE 80
