FROM node:14.17.0-alpine3.13 as build-stage

WORKDIR /workspace

RUN npm install -g @angular/cli
COPY package*.json ./
RUN npm install
COPY . ./
RUN ng build --prod


FROM nginx:1.19.10-alpine

COPY ./nginx.conf  /etc/nginx/conf.d/default.conf
COPY --from=build-stage /app/dist/app/*   /usr/share/nginx/html/

EXPOSE 80
