FROM node:15.14.0-alpine3.10 as build-stage
WORKDIR /app

COPY package*.json ./
RUN npm install
RUN npm install -g @angular/cli
COPY . .
RUN ng build --prod


FROM nginx:1.19.10-alpine

RUN addgroup app && adduser -S -G app app
WORKDIR /home/app
USER app

COPY ./nginx.conf  /etc/nginx/conf.d/default.conf
COPY --from=build-stage /app/dist/app/*   /usr/share/nginx/html/

EXPOSE 8080
